/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AppInfo {
  id: string
  name: string
  launchPath: string
  workingDirectory?: string
  iconPath?: string
  source: string
}
export interface ScreenshotPayload {
  width: number
  height: number
  x: number
  y: number
  buffer: Buffer
  mimeType: string
}
export interface ClipboardItem {
  sequence: number
  timestamp: number
  format: string
  text?: string
  image?: Buffer
}
export declare function scanApps(): Promise<Array<AppInfo>>
export declare function captureMonitorScreenshot(): Promise<ScreenshotPayload>
export declare function subscribeClipboard(callback: (err: Error | null, arg: ClipboardItem) => any): void
export declare function unsubscribeClipboard(): void
export declare function version(): string
